### ISSUE TITLE
What are the special preprocessing steps to exclude code snippets?

### ISSUE THREAD

**Issue by nasifimtiazohi** [senticr/SentiCR#1]
Hi there,

In your documentation, you mention about special preprocessing steps for the texts to exclude code snippets in this project. Is it possible to give me an idea on how you did this? 

Looking at the code, I got the part where you included programming language terms in your mystop keyword list and told your training model to ignore that.  Although that is not a very comprehensive list, as our problem is to exclude code snippets which can belong to any language.

Did I miss any other part? It would be really helpful if you share your logic on how you implemented this part of your program?
@senticr  @dialdroid-android

**Comment by amiangshu** [comment]
Please check our paper for more details (https://amiangshu.com/papers/senticr-ase.pdf). We included most of the keywords from C, C++, Java, and PHP, as the projects in our empirical study was written in those languages. Since it's open source, you can add other keywords. Please note that our approach will only work for sentiment analysis. If you need to separate code snippets, please check: Alberto Bacchelli, Michele Lanza, and Romain Robbes. 2010. Linking e-mails and source code artifacts. In Proceedings of the 32nd ACM/IEEE International Conference on Software Engineering - Volume 1 (ICSE '10)
